# Generated by Django 3.0.3 on 2020-10-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_exam_correctoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CorrectOption',
            field=models.CharField(max_length=100),
        ),
    ]
