# Generated by Django 3.0.3 on 2020-10-09 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201009_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Option1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='CorrectOption',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Option3',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Option4',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Question',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 11, 55, 12, 537007)),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Option1', models.CharField(max_length=200)),
                ('Option2', models.CharField(max_length=200)),
                ('Option3', models.CharField(max_length=200)),
                ('Option4', models.CharField(max_length=200)),
                ('CorrectOption', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Exam')),
            ],
        ),
    ]
