# Generated by Django 3.0.3 on 2020-10-09 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201009_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 12, 5, 43, 67073)),
        ),
    ]
