# Generated by Django 3.0.3 on 2020-10-09 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201009_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 12, 37, 29, 308505)),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 12, 37, 29, 308470)),
        ),
    ]
