# Generated by Django 3.0.3 on 2020-10-09 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201009_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 16, 21, 0, 934246)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 16, 21, 0, 934218)),
        ),
    ]
