# Generated by Django 3.0.3 on 2020-10-09 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201009_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 16, 27, 10, 170504)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 16, 27, 10, 170474)),
        ),
    ]
