# Generated by Django 3.0.3 on 2020-10-09 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201009_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='result',
            name='idt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 17, 56, 4, 642556)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 17, 56, 4, 642520)),
        ),
    ]
